apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd-demo

resources:
- deployment-v1.yaml
- deployment-v2.yaml
- service.yaml
- ingress.yaml

images:
- name: hello-gitops
  newName: victoriar18/hello-gitops
  newTag: 0ab696586f71babba99f442c5254f0a4c97dddea
