apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hello-gitops

resources:
- deployment-v1.yaml
- deployment-v2.yaml
- service.yaml
- ingress.yaml

images:
- name: hello-gitops
  newName: victoriar18/hello-gitops
  newTag: 25eda5ead787daba9fb972e4e0e3160d3b360a48
