apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd-demo

resources:
- deployment-v1.yaml
- deployment-v2.yaml
- service.yaml
- ingress.yaml

images:
- name: hello-gitops
  newName: victoriar18/hello-gitops
  newTag: dab971872d63deade76cecbb51d233de13c589cc
