apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-gitops
  namespace: argocd-demo
spec:
  project: default
  source:
    repoURL: 'https://github.com/viktoria-rybenchuk/ci-cd-deployment-strategy'
    targetRevision: main
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
